### ISSUE TITLE
JS error voxeet-sdk

### ISSUE THREAD

**Issue by varundabke** [dolbyio-samples/comms-app-react-events#19]
Getting following error on page load.
This is default project install - not made any changes. Please guide.

voxeet-sdk.js:2 Uncaught TypeError: Cannot set properties of undefined (setting 'ondevicechange')
    at fu.onDeviceChange (voxeet-sdk.js:2:1014310)
    at new is (voxeet-sdk.js:2:973249)
    at new Ml (voxeet-sdk.js:2:1054299)
    at voxeet-sdk.js:2:1057980
    at voxeet-sdk.js:2:1058232
    at voxeet-sdk.js:2:1058245
    at voxeet-sdk.js:2:81
    at ../node_modules/@voxeet/voxeet-web-sdk/dist/voxeet-sdk.js (voxeet-sdk.js:2:198)
    at __require (chunk-AC2VUBZ6.js?v=c3afe662:11:50)
    at jsx-runtime.js:7:1
onDeviceChange @ voxeet-sdk.js:2
is @ voxeet-sdk.js:2
Ml @ voxeet-sdk.js:2
(anonymous) @ voxeet-sdk.js:2
(anonymous) @ voxeet-sdk.js:2
(anonymous) @ voxeet-sdk.js:2
(anonymous) @ voxeet-sdk.js:2
../node_modules/@voxeet/voxeet-web-sdk/dist/voxeet-sdk.js @ voxeet-sdk.js:2
__require @ chunk-AC2VUBZ6.js?v=c3afe662:11
(anonymous) @ jsx-runtime.js:7
voxeet-sdk.js:2 Uncaught (in promise) TypeError: Cannot read properties of undefined (reading 'enumerateDevices')
    at voxeet-sdk.js:2:1008175
    at Generator.next (<anonymous>)
    at voxeet-sdk.js:2:1007829
    at new Promise (<anonymous>)
    at uu (voxeet-sdk.js:2:1007574)
    at hu (voxeet-sdk.js:2:1008103)
    at new fu (voxeet-sdk.js:2:1008722)
    at new Ml (voxeet-sdk.js:2:1054279)
    at voxeet-sdk.js:2:1057980
    at voxeet-sdk.js:2:1058232

**Comment by dubeyShivank** [comment]
Hi there, thanks for reaching out! Lets see what the root cause is - Can you tell me what steps you undertook?

**Comment by varundabke** [comment]
Thanks for reply!
I have downloaded code from github on a digitialocean ubuntu server. 
Did 'yarn' on the root folder.
( I migt have done 'yarn build' after that - but dont remember clearly )
Then did 'yarn dev' in 'events' folder.
Opened server-ip-address:3000 in browser - thats where I get the JS error and page remains white.

**Comment by dubeyShivank** [comment]
@varundabke I have two questions based on this - 

*Can we get some more information on your browser and OS?
* Does this work on a different machine? 
My theory is that you probably ran this on a browser with no camera/mic attached to the host (or virtual) machine, or the permissions were lacking at an OS level.

**Comment by varundabke** [comment]
> @varundabke I have two questions based on this -
> 
> *Can we get some more information on your browser and OS?
> 
> * Does this work on a different machine?
>   My theory is that you probably ran this on a browser with no camera/mic attached to the host (or virtual) machine, or the permissions were lacking at an OS level.

Thanks for responding.
I think there are two issues:
1) One desktop chome - it is white screen and on android chrome , app was throwing error message that VITE_CLIENT_ACCESS_TOKEN was needed. ( It is now added to .env )
2) This is more important - we need the server to start default on httpS - because as I understand camera and mic perssion needs httpS protocal. **How can we start the server on httpS ?**

Thanks!

**Comment by dubeyShivank** [comment]
Hey! Thanks for getting in touch again.

Ok, so after adding the access token to the `.env` file, did you observe a white screen on Android chrome as well?


Re securing with https - I'll pass you onto the digital ocean forums, as they've explained it over there :)

https://www.digitalocean.com/community/tutorials/how-to-secure-apache-with-let-s-encrypt-on-ubuntu-20-04

**Comment by varundabke** [comment]
> Hey! Thanks for getting in touch again.
> 
> Ok, so after adding the access token to the `.env` file, did you observe a white screen on Android chrome as well?
> 
> Re securing with https - I'll pass you onto the digital ocean forums, as they've explained it over there :)
> 
> https://www.digitalocean.com/community/tutorials/how-to-secure-apache-with-let-s-encrypt-on-ubuntu-20-04

It is still white on chrome desktop. On android chrome it does show some broken UI.

For https - thanks for the reference. I am aware of getting certificate. But not sure how to include it when running with 'yarn dev' . 
What is the standard deployment process , can we do it just with node.js express? How do you reccomend?

Thanks

**Comment by dubeyShivank** [comment]
Could I get a screenshot of both Android and desktop, please? I want to understand if it's even rendering on android and how broken does broken mean :) 

Yes, you can do it with standard node express - there's some built-in capabilities as well. I'm not sure what your complete setup is like, but if it is as self managed as it seems, then follow this guide 

https://adamtheautomator.com/https-nodejs/

**Comment by varundabke** [comment]
> Could I get a screenshot of both Android and desktop, please? I want to understand if it's even rendering on android and how broken does broken mean :)
> 
> Yes, you can do it with standard node express - there's some built-in capabilities as well. I'm not sure what your complete setup is like, but if it is as self managed as it seems, then follow this guide
> 
> https://adamtheautomator.com/https-nodejs/

Thanks.
![dolby_io](https://github.com/dolbyio-samples/comms-app-react-events/assets/8374300/0cb4d5ea-3c63-48fc-8337-fe7dbe440442)
Mic and video permissions are NOT asked after this page loads, and also the controls dont work.
About HTTPS, I am looking for answers specific to this project 'comms-app-react-events' . Since this works on webrtc and audio and video - generally these projects support https by default. So how do we run this application in httpS ? Or will it take significant modifications in code to make it work?
Thanks again.

**Comment by dubeyShivank** [comment]
Thanks @varundabke. We are currently working on making this app mobile responsive, and once that's ready you will be able to load the controls on mobile and navigate this app. 

With specific regards to https - yes, you are correct that webRTC-based apps need https in order to run successfully. The project needs to be hosted on a server that has valid https certificates, signed by a trusted authority. You're most likely correct that it is the reason the app isn't working on Android Chrome for you, as the browser can't validate the cert chain from your self-hosted instance.  Sorry for sending you the previous link before, having now understood what you're after, it wasn't the right solution. 

Coming back to the actual https problem - The issue here is that the server needs to be trusted by the browser, not the app itself. I understand that your app is hosted on an ubuntu server running an express instance. So bundling https certs with the app won't fix your problem. You need to use something like [ngrok](https://ngrok.com/) while you're developing and debugging things. In saying that, my personal recommendation to you would be to use something like netlify or heroku to manage the process of hosting your app on a trusted server. We have instructions on how to deploy your own fork in our read me. 

Hope this helps
